### PR TITLE
Add npm auth for our private packages

### PR DESCRIPTION
**Pull request by Simonpedro**
https://app.asana.com/0/1203931215747752/1204957435175022/f

### CODE REVIEW

**Comment by Simonpedro** [comment]
This should be merged after https://github.com/BuoySoftware/BuoyRails/pull/8998 and https://github.com/BuoySoftware/Infirmary/pull/815 have been merged, both updating the ci config giles

**Review by dgalarza — APPROVED** [review]

**Comment by cornshuckin2** [comment]
> Am I missing any other repo?

Looks like you might be missing wharf https://github.com/search?q=org%3ABuoySoftware%20BuoySoftware%2Fgithub-actions%2Fsetup-node%40main&type=code

**Comment by Simonpedro** [comment]
> > Am I missing any other repo?
> 
> Looks like you might be missing wharf https://github.com/search?q=org%3ABuoySoftware%20BuoySoftware%2Fgithub-actions%2Fsetup-node%40main&type=code

Thank you!

**Comment by Simonpedro** [comment]
@cornshuckin2 I ended up making the input optional and the action conditional, since we don't need authentication in all repos, only on the ones relying in private packages (BuoyRails and Infirmary currently)

**Pull request merged**
